# Dockerfile.job

# 1. 베이스 이미지 설정
FROM python:3.9-slim

# 2. 환경 변수 설정
ENV PYTHONUNBUFFERED True

# 3. 작업 디렉토리 설정
WORKDIR /app

# 4. requirements.txt 복사 및 라이브러리 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. 필요한 파이썬 스크립트들을 모두 복사
COPY cache_warmer.py .
COPY hatena_client.py .

# 6. Cloud Run Job 실행 명령어
CMD ["python", "cache_warmer.py"]